auto: true
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
rdiscount:
  extensions: [smart]

name: Swift
url: http://theycallmeswift.com
description: Lab notes and scribbles from a mad-scientist at play.
email: swift@theycallmeswift.com
twitter: SwiftAlphaOne
github: theycallmeswift
gravatar_url: http://www.gravatar.com/avatar/10831877bd394c902f1dda20524c86d6
